apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-config
  namespace: namespace-workflow-1745842842039
  labels:
    app.kubernetes.io/name: testing
    kubernetes.azure.com/generator: devhub
data: