apiVersion: v1
kind: Service
metadata:
  name: testing
  namespace: namespace-workflow-1745842842039
  labels:
    app.kubernetes.io/name: testing
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: testing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080